### ISSUE TITLE
Allow copy paste for block arguments

### ISSUE THREAD

**Issue by mrosseel** [davidferguson/pibakery#108]
Maybe it's a local problem, but I can't copy paste passwords, network names, file names into the parameter fields of the blocks.

Is this normal? If so, consider this a feature request to fix this, because it's tedious to type long passwords/filenames by hand.

**Comment by exocode** [comment]
What I found out: It's possible to drag-and-drop it into the field. (I use a mac)

**Comment by davidferguson** [comment]
PiBakery v2 has a different copy-paste mechanism, which should now be working. I've not created a release for this yet, as I hope to fix a few more things first.

**Comment by theronic** [comment]
This is especially troublesome for SSH keys.

**Comment by tvories** [comment]
Same issue on mac.  Any chance for an update to the v2 release?

**Comment by RobertStickney** [comment]
Paste is still not working in v2 on Mac Catalina 10.15.6.  Drag & drop working.

**Comment by raiman264** [comment]
just found that it is already fixed but the release binaries are not updated, you need to install from source
